name: playground
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

